name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Updated to Python 3.11

    # Install dependencies (for validation)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install EB CLI
    - name: Install EB CLI
      run: |
        pip install awsebcli

    # Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Set environment variables in Elastic Beanstalk
    - name: Set Environment Variables
      run: |
        eb setenv FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} AIRTABLE_PAT=${{ secrets.AIRTABLE_PAT }} AIRTABLE_BASE_ID=${{ secrets.AIRTABLE_BASE_ID }}

    # Deploy to Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -p python-3.11 msc-project --region us-east-1
        eb deploy msc-project-env
      env:
        AWS_DEFAULT_REGION: us-east-1

    # Validate deployment
    - name: Validate Deployment
      run: |
        curl -f http://msc-project-env.<random-string>.us-east-1.elasticbeanstalk.com || exit 1